jobs:
  build: # name of your job
    machine: # executor type
      image: ubuntu-2004:202010-01 # # recommended linux image - includes Ubuntu 20.04, docker 19.03.13, docker-compose 1.27.4

    steps:
        # Commands run in a Linux virtual machine environment
        # Checkout the code as the first step.
        - checkout
        - run:
           name: Build docker image
           command: docker build -t infamia/supportportal:$CIRCLE_SHA1 .
        - run:
           name: Login to docker hub 
           command: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        - run:
           name: Push docker image
           command: docker push infamia/supportportal:$CIRCLE_SHA1
     
     
        
       